config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'
  root 'posts#index'
  get 'users/show'
  get '/signup', to: 'users#new'
  get 'users/edit'
  get    '/login',   to: 'sessions#new'
  get    '/logged_in_user', to: 'sessions#logged_in_user'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :edit_avatar
      patch :update_avatar
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :password_resets, only: %i[new create edit update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
      get :edit_images
      patch :update_images
    end
  end
  get 'tags/:tag', to: 'posts#search_tags', as: :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 86 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save!
      render :index
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/views/comments/_form.html.haml
= form_for([@post, @comment],:html => {:class => "form-inline mt-3 mb-3"}, remote: true) do |f|
  - if logged_in?
    .form-group.comment-input-wrapper
      = f.text_field :content, placeholder: "コメントする", maxlength: "86", class: "form-control comment-input mr-2"
    .form-group.comment-btn-wrapper 
      = f.submit '送信', class: "btn btn-success btn-circle comment-btn"
  - else
    .form-group.comment-input-wrapper
      = f.text_field :content, placeholder: "コメント機能を利用するにはログインしてください", class: "form-control comment-input mr-2", disabled: true
    .form-group.comment-btn-wrapper 
      = f.submit '送信', class: "btn btn-success btn-circle comment-btn", disabled: true

app/views/comments/_index.html.haml
- unless comments.blank?
  - comments.reverse_each do |c|
    .row.mb-4
      .col-3.col-sm-1.col-md-2.col-lg-1
        - if c.user.avatar?
          %div{ style: "background-image: url(#{c.user.avatar.thumb.url})", class: 'thumb-cercle thumb-cercle_comment' }
        -else
          = render 'comments/no_image_avatar'
      .col-9.col-sm-11.col-md-10.col-lg-11
        .comment-user-name
          %a{href: "/users/#{c.user.id}"}
            = c.user.name
        .comment-content
          = c.content
        - if c.user == current_user
          = link_to '削除', post_comment_path(c.post_id, c.id), method: :delete, remote: true, class: 'link_text'
- else
  .comments-blank-text.mt-4.mb-4
    まだコメントがありません

app/views/comments/_no_image_avatar.html.haml
%div{ style: "background-image: url(http://d498ars0bd21o.cloudfront.net/assets/no_image.jpg)", class: 'thumb-cercle thumb-cercle_comment' }

app/views/comments/index.js.haml
$("#comments-area").html("#{j(render 'index', comments: @comment.post.comments)}")
$(".comment-input").val('')