config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'
  root 'posts#index'
  get 'users/show'
  get '/signup', to: 'users#new'
  get 'users/edit'
  get    '/login',   to: 'sessions#new'
  get    '/logged_in_user', to: 'sessions#logged_in_user'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :edit_avatar
      patch :update_avatar
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :password_resets, only: %i[new create edit update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
      get :edit_images
      patch :update_images
    end
  end
  get 'tags/:tag', to: 'posts#search_tags', as: :tag
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %hr
    .copyright
      Portfolio

app/views/layouts/_header.html.haml
%nav.navbar.navbar-dark.navbar-expand-md.bg-primary.text-nowrap
  .container
    %a.navbar-brand{href: '/', style: 'font-family: ABeeZee, sans-serif'}
      %strong
        Portfolio
    %button.navbar-toggler{'data-toggle' => 'collapse', 'data-target' => '#navcol-1'}
      %span.sr-only
        Toggle navigation
      %span.navbar-toggler-icon
    %div.collapse.navbar-collapse#navcol-1
      %ul.nav.navbar-nav.ml-auto
        - if logged_in?
          %li.nav-item{role: 'presentation'}
            %a.nav-link{href: "/posts/new"}
              投稿
          %li.dropdown
            %a#navbar-user-toggle.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown', 'class' => 'nav-link'}
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'マイページ', current_user
              %li
                = link_to 'プロフィール編集', edit_user_path(current_user)
              %li.divider
              %li
                = link_to 'ログアウト', logout_path, method: :delete    
        - else
          %li.nav-item{role: 'presentation'}
            %a.nav-link{href: '/users/new'}
              サインイン
          %li
            = link_to 'ログイン', login_path, class: 'nav-link'
        %li.search-box.mt-2
          = search_form_for @q, url: posts_path do |f|
            = f.text_field :title, placeholder: '検索', value: @words
            = button_tag class: 'search-btn' do
              %i.fa.fa-search
  
            

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, user-scalable=no' }   
    #{csrf_meta_tags}
    #{csp_meta_tag}
    #{stylesheet_link_tag    'application', media: 'all'}
    #{javascript_include_tag 'application', 'data-turbolinks-track': 'reload'}
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

  %body
    #{render 'layouts/header'}
    .container
      - flash.each do |message_type, message|
        #{content_tag(:div, message, class: "alert alert-#{message_type}")}
      #{yield}
    #{render 'layouts/footer'}

  